language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml --globals-backup --bootstrap ./tests/bootstrap.php ./tests/

after_script:
  - if [[ "`php --version`" != *HipHop* ]] ; then php vendor/bin/coveralls -v ; fi
  - if [[ "`php --version`" != *HipHop* ]] ; then php vendor/bin/ocular code-coverage:upload --format=php-clover ./build/logs/clover.xml ; fi
