language: php
php:
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml --bootstrap ./tests/bootstrap.php ./tests/

after_script:
  - php vendor/bin/coveralls -v
  - php vendor/bin/ocular code-coverage:upload --format=php-clover ./build/logs/clover.xml
