language: php
php:
  - 7.2
  - 7.3

install:
  - composer install

before_script:
  - mkdir -p build/logs

script:
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml --globals-backup --bootstrap ./tests/bootstrap.php ./tests/

after_script:
  - php vendor/bin/php-coveralls
  - php vendor/bin/ocular code-coverage:upload --format=php-clover ./build/logs/clover.xml
